INSERT INTO servers (server_name, region, operating_system) VALUES
('Server A', 'US-East', 'Linux'),
('Server B', 'US-West', 'Windows Server'),
('Server C', 'Europe', 'Linux'),
('Server D', 'Asia', 'Windows Server'),
('Server E', 'Australia', 'Linux'),
('Server F', 'South America', 'Windows Server'),
('Server G', 'Africa', 'Linux'),
('Server H', 'Middle East', 'Windows Server'),
('Server I', 'Central America', 'Linux'),
('Server J', 'Caribbean', 'Windows Server'),
('Server K', 'US-East', 'Linux'),
('Server L', 'US-West', 'Windows Server'),
('Server M', 'Europe', 'Linux'),
('Server N', 'Asia', 'Windows Server'),
('Server O', 'Australia', 'Linux'),
('Server P', 'South America', 'Windows Server'),
('Server Q', 'Africa', 'Linux'),
('Server R', 'Middle East', 'Windows Server'),
('Server S', 'Central America', 'Linux'),
('Server T', 'Caribbean', 'Windows Server')
ON CONFLICT DO NOTHING;
